### PR TITLE
Colour barchart by region selected

### PR DESCRIPTION
**Pull request by seb231**

### CODE REVIEW

**Comment by sunnytownsend** [comment]
missing the nhs_region argument when run the function (line 158)

**Comment by sunnytownsend** [comment]
Looks great! One concern though - use a different colours than greens - using green makes me think it matches the map prevalence because that is also green

**Comment by seb231** [comment]
This is kind of what we were going for @sunnytownsend, but clearly there needs to be more discussion around it

**Comment by sunnytownsend** [comment]
:shipit:

**Pull request merged**
